run:
  timeout: 10m
  skip-dirs:
    - vendor
    - examples
    - cmd/api-examples
    - tests/load
  skip-files:
    - ".*_test.go"
    - "mock_*.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Core linters
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Vet examines Go source code
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Go static analysis
    - typecheck         # Parse and type-check Go code
    - unused            # Check for unused constants, variables, functions and types
    
    # Formatting
    - gofmt             # Check whether code was gofmt-ed
    - goimports         # Check import statements are formatted according to the 'goimport' command
    
    # Code quality
    - misspell          # Finds commonly misspelled English words
    - gosec             # Security-focused linter
    - gocritic          # Provides diagnostics that check for bugs, performance and style issues
    - revive            # Fast, configurable, extensible, flexible, and beautiful linter for Go
    
    # Complexity
    - gocyclo           # Computes and checks the cyclomatic complexity of functions
    - gocognit          # Computes and checks the cognitive complexity of functions
    
    # Error handling
    - goerr113          # Check the errors handling expressions
    
    # Performance
    - prealloc          # Find slice declarations that could potentially be preallocated
    
    # Style
    - stylecheck        # Stylecheck is a replacement for golint
    - whitespace        # Tool for detection of leading and trailing whitespace

  disable:
    - varnamelen        # Too strict for this codebase
    - exhaustive        # Too strict for this codebase
    - cyclop            # Duplicate of gocyclo
    - funlen            # Too strict for this codebase
    - lll               # Line length check (handled by formatter)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (handled by errcheck)
      - G204  # Subprocess launched with variable (needed for dynamic commands)

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
      - whyNoLint

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  revive:
    rules:
      - name: exported
        arguments: [false]
      - name: package-comments
        disabled: true
      - name: var-naming
        arguments: [["ID"], ["API", "HTTP", "JSON", "XML", "URL"]]

  stylecheck:
    checks: ["all", "-ST1003", "-ST1000"]

  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this codebase

  whitespace:
    multi-if: false
    multi-func: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - gocyclo
        - gocognit
    
    # Exclude known issues in generated files
    - path: mock_.*\.go
      linters:
        - all
    
    # Exclude some checks for main.go files
    - path: main\.go
      linters:
        - gocritic
        - gocyclo
    
    # Exclude complexity checks for certain large functions that are inherently complex
    - text: "function .* is too complex"
      linters:
        - gocyclo
        - gocognit
      path: ".*/(handlers|middleware|processor).*\\.go"

  # Show only new issues if this is a PR
  new-from-rev: origin/main

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - misspell
      severity: warning
    - linters:
        - gocritic
      severity: info