global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Hotel Reviews API metrics
  - job_name: "hotel-reviews-api"
    static_configs:
      - targets: ["hotel-reviews-api:8080"]
    metrics_path: /api/v1/metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL metrics (using postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (using redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # MinIO metrics
  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter (for system metrics)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (using nginx_exporter)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana metrics
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # AlertManager metrics
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Jaeger metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s