# Production Configuration for Hotel Reviews Microservice
# This file contains production-ready settings with security, performance, and reliability optimizations

# Database Configuration
database:
  host: "${DATABASE_HOST}"
  port: 5432
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  name: "${DATABASE_NAME}"
  ssl_mode: "require"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: "30m"
  conn_max_idle_time: "10m"
  timezone: "UTC"
  log_level: "error"

# S3 Configuration
s3:
  region: "${AWS_REGION}"
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  session_token: "${AWS_SESSION_TOKEN}"
  bucket: "${S3_BUCKET}"
  use_ssl: true
  force_path_style: false
  timeout: "60s"
  retry_count: 5
  retry_delay: "2s"
  upload_part_size: 10485760  # 10MB
  download_part_size: 10485760 # 10MB

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  shutdown_timeout: "60s"
  max_header_bytes: 2097152 # 2MB
  enable_cors: true
  enable_gzip: true
  enable_metrics: true
  enable_pprof: false
  tls_cert_file: "${TLS_CERT_FILE}"
  tls_key_file: "${TLS_KEY_FILE}"
  trusted_proxies:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"

# Logging Configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  enable_caller: true
  enable_stacktrace: false

# Cache Configuration
cache:
  type: "redis"
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  database: 0
  pool_size: 50
  min_idle_conns: 10
  dial_timeout: "10s"
  read_timeout: "5s"
  write_timeout: "5s"
  ttl: "6h"
  max_memory: 1073741824 # 1GB

# Metrics Configuration
metrics:
  enabled: true
  type: "prometheus"
  host: "0.0.0.0"
  port: 9090
  path: "/metrics"
  namespace: "hotel_reviews"
  service_name: "hotel-reviews-api"
  environment: "production"
  version: "${APP_VERSION}"

# Notification Configuration
notification:
  email:
    enabled: true
    host: "${SMTP_HOST}"
    port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    from: "noreply@hotelreviews.com"
    use_tls: true
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#hotel-reviews-alerts"
    username: "Hotel Reviews Bot"
    icon_emoji: ":hotel:"

# Processing Configuration
processing:
  batch_size: 5000
  worker_count: 8
  max_file_size: 524288000 # 500MB
  processing_timeout: "60m"
  max_retries: 5
  retry_delay: "10s"
  enable_validation: true
  enable_duplicate_check: true
  temp_directory: "/tmp/hotel-reviews"

# Security Configuration
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiration: "12h"
  rate_limit: 10000
  rate_limit_window: "1h"
  enable_api_key: true
  api_key_header: "X-API-Key"
  enable_encryption: true
  encryption_key: "${ENCRYPTION_KEY}"

# Authentication Configuration
auth:
  jwt_secret: "${AUTH_JWT_SECRET}"
  jwt_issuer: "hotel-reviews-api.production"
  access_token_expiry: "15m"
  refresh_token_expiry: "168h" # 7 days
  max_login_attempts: 5
  login_attempt_window: "15m"
  account_lock_duration: "60m"
  password_min_length: 12
  password_max_length: 128
  require_strong_password: true
  enable_two_factor: true
  enable_email_verification: true
  enable_password_reset: true
  enable_session_cleanup: true
  session_cleanup_interval: "30m"
  enable_audit_logging: true
  enable_rate_limiting: true
  bcrypt_cost: 14
  api_key_length: 64
  api_key_prefix: "hr_prod_"
  default_role: "user"

# Kafka Configuration
kafka:
  brokers:
    - "${KAFKA_BROKER_1}"
    - "${KAFKA_BROKER_2}"
    - "${KAFKA_BROKER_3}"
  review_topic: "hotel-reviews-production"
  processing_topic: "hotel-reviews-processing-production"
  dead_letter_topic: "hotel-reviews-dlq-production"
  consumer_group: "hotel-reviews-consumer-production"
  batch_size: 1000
  batch_timeout: "5s"
  max_retries: 5
  retry_delay: "5s"
  enable_sasl: true
  sasl_username: "${KAFKA_SASL_USERNAME}"
  sasl_password: "${KAFKA_SASL_PASSWORD}"
  enable_tls: true
  max_message_size: 10485760 # 10MB
  compression_type: "snappy"
  producer_flush_timeout: "30s"
  consumer_timeout: "30s"
  enable_idempotence: true
  partitions: 12
  replication_factor: 3