apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-reviews-api-pdb
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: hotel-reviews
      component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-reviews-worker-pdb
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hotel-reviews
      component: worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-reviews-postgres-pdb
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: postgres
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hotel-reviews
      component: postgres
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-reviews-redis-pdb
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: redis
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hotel-reviews
      component: redis
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hotel-reviews-kafka-pdb
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: kafka
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: hotel-reviews
      component: kafka