apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-postgres-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-redis-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-kafka-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-zookeeper-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-prometheus-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotel-reviews-grafana-pvc
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard