apiVersion: v1
kind: Secret
metadata:
  name: hotel-reviews-secrets
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: api
type: Opaque
data:
  # Database credentials (base64 encoded)
  database-user: aG90ZWxfcmV2aWV3cw==  # hotel_reviews
  database-password: c2VjdXJlX3Bhc3N3b3Jk  # secure_password
  
  # Redis password (base64 encoded)
  redis-password: ""  # empty for development
  
  # S3 credentials (base64 encoded)
  s3-access-key-id: eW91cl9hY2Nlc3Nfa2V5  # your_access_key
  s3-secret-access-key: eW91cl9zZWNyZXRfa2V5  # your_secret_key
  
  # JWT secret (base64 encoded)
  jwt-secret: eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV90aGF0X3Nob3VsZF9iZV9hdF9sZWFzdF8zMl9jaGFyYWN0ZXJzX2xvbmc=  # your_super_secret_jwt_key_that_should_be_at_least_32_characters_long
  
  # Kafka SASL credentials (base64 encoded)
  kafka-sasl-username: ""  # empty for development
  kafka-sasl-password: ""  # empty for development
  
  # Notification credentials (base64 encoded)
  email-username: eW91cl9lbWFpbEBnbWFpbC5jb20=  # your_email@gmail.com
  email-password: eW91cl9wYXNzd29yZA==  # your_password
  
  # Slack webhook URL (base64 encoded)
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDS1dFQkhPT0s=  # https://hooks.slack.com/services/YOUR/SLACKWEBHOOK
  
  # TLS certificates (base64 encoded)
  tls-cert: ""  # TLS certificate content
  tls-key: ""   # TLS private key content
---
apiVersion: v1
kind: Secret
metadata:
  name: hotel-reviews-registry-secret
  namespace: hotel-reviews
  labels:
    app: hotel-reviews
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ5b3VyX2RvY2tlcl91c2VybmFtZSIsInBhc3N3b3JkIjoieW91cl9kb2NrZXJfcGFzc3dvcmQiLCJlbWFpbCI6InlvdXJfZW1haWxAZXhhbXBsZS5jb20iLCJhdXRoIjoiZVc5MWNsOWtiMk5yWlhKZmRYTmxjbTVoYldVNmVXOTFjbDlrYjJOclpYSmZjR0Z6YzNkdmNtUT0ifX19