apiVersion: v1
kind: Namespace
metadata:
  name: hotel-reviews-staging
  labels:
    app: hotel-reviews
    environment: staging
    tier: staging
    cost-center: development
    team: platform-engineering
  annotations:
    app.kubernetes.io/environment: staging
    config.kubernetes.io/origin: staging
    contact: platform-team@hotel-reviews.com
    description: "Staging environment for Hotel Reviews microservice"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hotel-reviews-staging-quota
  namespace: hotel-reviews-staging
  labels:
    app: hotel-reviews
    environment: staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
    pods: "20"
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"
    count/jobs.batch: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hotel-reviews-staging-limits
  namespace: hotel-reviews-staging
  labels:
    app: hotel-reviews
    environment: staging
spec:
  limits:
    - default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
    - max:
        cpu: 1000m
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
      type: Container
    - max:
        storage: 20Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim